FROM python:3.13-slim-bookworm

COPY --from=ghcr.io/astral-sh/uv:0.4.29 /uv /uvx /bin/

WORKDIR /app

COPY . /app

ENV PYTHONBUFFERED=1
ENV PYTHONDONTWRITEBYTECODE=1

RUN uv sync --locked

EXPOSE 8000

CMD uv run --no-dev manage.py collectstatic --noinput && uv run daphne sociallty.asgi:application -b 0.0.0.0 -p 8000
