services:
  web:
    build: .
    volumes:
      - ".:/app"
      - ".:/code"
    ports:
      - "${PORT}:8000"
    depends_on:
      - redis

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"