# Generated by Django 5.1.2 on 2025-05-25 12:18

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_messagereact'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserChannel',
            new_name='OnlineUser',
        ),
    ]
