# Generated by Django 5.1.2 on 2025-05-28 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_rename_userchannel_onlineuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messagereact',
            old_name='reacted_at',
            new_name='created_at',
        ),
    ]
