# Generated by Django 5.0.4 on 2024-04-20 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0004_rename_view_post_visiblety'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='visiblety',
            new_name='visibility',
        ),
    ]
