# Generated by Django 5.0.4 on 2024-05-24 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0009_alter_photo_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='visibility',
            field=models.CharField(choices=[('public', 'public post'), ('private', 'private'), ('friends only', 'friends only')], default='public', max_length=13),
        ),
    ]
