# Generated by Django 5.0.4 on 2024-05-27 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0012_video_poster'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='post',
        ),
        migrations.CreateModel(
            name='Post_Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.FileField(blank=True, null=True, upload_to='posts_media/')),
                ('poster', models.ImageField(blank=True, null=True, upload_to='vids_posters/')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='main_page.post')),
            ],
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
