# Generated by Django 5.0.4 on 2024-05-27 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0013_remove_video_post_post_content_delete_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_content',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='main_page.post'),
        ),
    ]
