# Generated by Django 5.0.4 on 2024-05-27 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0014_alter_post_content_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post_content',
            name='content_type',
            field=models.CharField(choices=[('image', 'image'), ('video', 'video')], max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='post_content',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='posters/'),
        ),
    ]
