# Generated by Django 5.0.4 on 2024-05-29 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0015_post_content_content_type_alter_post_content_poster'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post_Content',
            new_name='PostContent',
        ),
    ]
