# Generated by Django 5.0.4 on 2024-05-31 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0016_rename_post_content_postcontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcontent',
            name='full_content_type',
            field=models.CharField(max_length=14, null=True),
        ),
    ]
