# Generated by Django 5.1.2 on 2024-10-18 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0017_postcontent_full_content_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='visibility',
            field=models.CharField(choices=[('Public', 'Public'), ('Private', 'Private'), ('Friends only', 'Friends Only')], default='Public', max_length=13),
        ),
        migrations.AlterField(
            model_name='postcontent',
            name='content_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video')], max_length=6, null=True),
        ),
    ]
