# Generated by Django 5.1.2 on 2024-10-18 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0018_alter_post_visibility_alter_postcontent_content_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('friends only', 'Friends Only')], default='public', max_length=13),
        ),
    ]
