# Generated by Django 5.1.2 on 2025-03-08 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0019_alter_post_visibility'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postcontent',
            old_name='content',
            new_name='video',
        ),
        migrations.AddField(
            model_name='postcontent',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='posters/'),
        ),
    ]
