# Generated by Django 5.1.2 on 2025-03-09 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0020_rename_content_postcontent_video_postcontent_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcontent',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='posts_media/images/'),
        ),
        migrations.AlterField(
            model_name='postcontent',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='posts_media/videos/'),
        ),
    ]
