# Generated by Django 5.1.2 on 2025-03-24 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0022_alter_like_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postcontent',
            name='poster',
        ),
    ]
