# Generated by Django 5.1.2 on 2025-07-02 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0023_remove_postcontent_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='ready',
            field=models.BooleanField(default=True, help_text='if the post is ready to be displayed'),
        ),
    ]
