# Generated by Django 5.0.4 on 2024-04-14 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_friends'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Friends',
            new_name='Friend',
        ),
    ]
