# Generated by Django 5.0.4 on 2024-04-27 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_socialuser_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialuser',
            name='birth',
            field=models.DateField(null=True),
        ),
    ]
