# Generated by Django 5.0.4 on 2024-04-27 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_socialuser_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialuser',
            name='profile_picture',
            field=models.ImageField(default='media/profile_pictures/unknown.png', upload_to='media/profile_pictures/'),
        ),
    ]
