# Generated by Django 5.0.4 on 2024-05-23 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_socialuser_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialuser',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
