# Generated by Django 5.0.4 on 2024-05-24 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_socialuser_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialuser',
            name='phone',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
