# Generated by Django 5.0.4 on 2024-05-31 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_socialuser_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='socialuser',
            old_name='date_joined',
            new_name='created_at',
        ),
    ]
