# Generated by Django 5.0.4 on 2024-05-31 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_rename_date_joined_socialuser_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friend',
            old_name='created_at',
            new_name='friends_since',
        ),
    ]
