# Generated by Django 5.1.2 on 2025-01-26 16:55

from django.db import migrations

from users.models import SocialUser, SocialUserSettings

def create_defult_settings(apps, schema) -> None:
    
    for user in SocialUser.objects.all().iterator(30):
        if not hasattr(user, 'settings'):
            print(f"creating settings for {user}")
            SocialUserSettings.objects.create(user=user)

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_alter_usercode_code_socialusersettings'),
    ]

    operations = [
        migrations.RunPython(create_defult_settings)
    ]
