# Generated by Django 5.1.2 on 2025-02-04 02:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_friendrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialuser',
            name='password',
            field=models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(8)]),
        ),
    ]
