# Generated by Django 5.1.2 on 2025-03-08 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_alter_socialuser_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialuser',
            name='profile_picture',
            field=models.ImageField(default='profile_pictures/dolru8slhdzk3boxztrv', upload_to='profile_pictures/'),
        ),
    ]
