# Generated by Django 5.1.2 on 2025-03-09 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_alter_socialuser_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialuser',
            name='profile_picture',
            field=models.ImageField(default='profile_pictures/unknown.png', upload_to='profile_pictures/'),
        ),
    ]
