# Generated by Django 5.1.2 on 2025-06-17 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_alter_socialuser_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialuser',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=10),
        ),
    ]
